version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - gfd:/etc/grafana
      - gfd:/var/log/grafana
      - gfd:/var/lib/grafana
    links:
      - influxdb
    ports:
      - "3000:3000"
    env_file: .env
  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - id:/var/lib/influxdb
    ports:
      - "8086:8086"
    env_file: .env
volumes:
  gfd:
  id:
