version: '2'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - gfd:/etc/grafana
      - gfd:/var/log/grafana
      - gfd:/var/lib/grafana
    links:
      - influxdb
    env_file: .env
    environment:
      VIRTUAL_HOST: grafana.elontie.club
      LETSENCRYPT_HOST: grafana.elontie.club
      LETSENCRYPT_EMAIL: "{$LETSENCRYPT_EMAIL}"
  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - id:/var/lib/influxdb
    env_file: .env
    environment:
      VIRTUAL_HOST: influxdb.elontie.club
      LETSENCRYPT_HOST: influxdb.elontie.club
      LETSENCRYPT_EMAIL: "{$LETSENCRYPT_EMAIL}"
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/etc/nginx/certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - '/etc/nginx/certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy
volumes:
  gfd:
  id:
